spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${{ env.spring.datasource.url }}:3306/bbodok?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${{ env.spring.datasource.username }}
    password: ${{ env.spring.datasource.password }}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        hbm2ddl:
          jdbc_metadata_extraction_strategy: individually
        format_sql: true
        show_sql: false
        order_inserts: true
        order_updates: true