spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${{ secrets.RDS_ENDPOINT }}:3306/bbodok?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${{ secrets.RDS_USERNAME }}
    password: ${{ secrets.RDS_PASSWORD }}
    ssh:
      tunnel:
        enabled: true
        host: ${{ secrets.EC2_PRIVATE_IP }}
        port: 22
        user: ec2-user
        key-file: ${{ PEM_KEY_PATH }}
        local-port: 22
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        hbm2ddl:
          jdbc_metadata_extraction_strategy: individually
        format_sql: true
        show_sql: false
        order_inserts: true
        order_updates: true