name: Java CI with Gradle - prod

on:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
env:
  RESOURCE_PATH: src/main/resources/application.yml
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Set yml file
        run: |
          mkdir -p src/main/resources
          echo "${{ secrets.APPLICATION_YML }}" | base64 --decode > src/main/resources/application.yml
          find src
      - name: Set firebase admin sdk file
        run: |
          mkdir -p src/main/resources
          echo "${{ secrets.FIREBASE_ADMIN_SDK }}" | base64 --decode > src/main/resources/o-vengers-prod-firebase-adminsdk-yyse1-7be18605af.json
          find src
      - name: Build with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: build